default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yryr_development

test:
  <<: *default
  database: yryr_test

production:
  <<: *default
  database: yryr_production
  username:
  password:
